[package]
name = "event-notification"
version = "0.1.0"
edition = "2024"
description = "A modular event notification system with multi-channel support"
license = "Apache-2.0 or MIT"
repository = "https://github.com/houseme/event-notification"

[dependencies]
tokio = { version = "1.44", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
uuid = { version = "1.16", features = ["v4", "serde"] }
chrono = { version = "0.4.40", features = ["serde"] }
reqwest = { version = "0.12.15", features = ["json"] }
axum = "0.8.3"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
thiserror = "2.0.12"
anyhow = "1.0.98"
parking_lot = "0.12.3"
tokio-util = "0.7.14"
async-trait = "0.1.88"

[dependencies.rdkafka]
version = "0.37.0"
features = ["tokio"]
optional = true

[dependencies.rumqttc]
version = "0.24"
optional = true

[features]
kafka = ["rdkafka"]
mqtt = ["rumqttc"]

[dev-dependencies]
tokio = { version = "1.44.2", features = ["test-util"] }